name: material_io_ext
description: It is a collection of extensions for creating widgets following material.io guidelines.
version: 0.0.4
homepage: https://github.com/betterx-io/material_io_ext

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
# flutter: